### ISSUE TITLE
Lightness in Lab

### ISSUE THREAD

**Issue by Santinell** [zeke/color-namer#1]
IMHO for determine color in L_a_b color space - Lightness is least important
So I think is needed reduce the L in Lab, for reduce its impact

**Comment by zeke** [comment]
Interesting. Care to send a pull request?

**Comment by Santinell** [comment]
I don't know true reducing coefficient, but  [L*0.5, a, b ] works better on my test colors.
I will try to explore it more.

**Comment by Santinell** [comment]
Reducing the "L" is not enough improves accuracy for my data :(
In wiki for color difference recommends using CIEDE2000 instead of CIE76 (Euclidean distance)
I found one implementation: https://github.com/markusn/color-diff

**Comment by zeke** [comment]
color-diff looks nice. Have you used it yet?

**Comment by Santinell** [comment]
Yes, but factor of rising accuracy for both algorithms is: the larger colors in palette - the more accurate definition of the color.
So now I choosing between using color difference and using some trees for storing colors (octree, kd-tree) and searching nearest neighbor.
